on: [workflow_dispatch, push]

name: 'Quick CI Tests'

jobs:
  gcd_test_job:
    timeout-minutes: 10
    runs-on: self-hosted
    name: 'ASIC test builds'
    steps:
      - uses: actions/checkout@v2
      - name: Checkout OR submodule
        run: git submodule update --init --recursive third_party/tools/openroad
      - run: |
          python3 -m venv create $GITHUB_WORKSPACE/clean_env --clear
          source $GITHUB_WORKSPACE/clean_env/bin/activate
          echo $VIRTUAL_ENV
          pip3 install -r $GITHUB_WORKSPACE/requirements.txt -e $GITHUB_WORKSPACE/.
          pytest -n 4 $GITHUB_WORKSPACE/tests/quick_tests/asic/
  fpga_test_job:
    timeout-minutes: 10
    runs-on: self-hosted
    name: 'FPGA test builds'
    steps:
      - uses: actions/checkout@v2
      - name: Checkout OR submodule
        run: git submodule update --init --recursive third_party/tools/openroad
      - run: |
          python3 -m venv create $GITHUB_WORKSPACE/clean_env --clear
          source $GITHUB_WORKSPACE/clean_env/bin/activate
          echo $VIRTUAL_ENV
          pip3 install -r $GITHUB_WORKSPACE/requirements.txt -e $GITHUB_WORKSPACE/.
          PATH="$HOME/OpenFPGA/openfpga:$PATH"
          pytest -n 4 $GITHUB_WORKSPACE/tests/quick_tests/fpga/
  python_test_job:
    timeout-minutes: 5
    runs-on: self-hosted
    name: 'Python unit tests'
    steps:
      - uses: actions/checkout@v2
      - name: Checkout OR submodule
        run: git submodule update --init --recursive third_party/tools/openroad
      - run: |
          python3 -m venv create $GITHUB_WORKSPACE/clean_env --clear
          source $GITHUB_WORKSPACE/clean_env/bin/activate
          pip3 install -r $GITHUB_WORKSPACE/requirements.txt -e $GITHUB_WORKSPACE/.
          pytest $GITHUB_WORKSPACE/tests/quick_tests/python/
